set nocompatible
let $MYVIMRC = expand('~/_vimrc')

source ~/_vimrc

setglobal errorformat=%f(%l):\ error\ %m,%-G%.%#

function! s:build_handmade()
  wall

  let nr = winnr()

  " open quickfix window in other split
  if &ft != 'qf'
    " switch to other window
    if winnr('$') > 1
      wincmd w
    else
      vsplit
    endif

    if &ft != 'qf'
      copen
      wincmd p
      close
    endif
  endif

  AsyncRun -post=silent\ doautocmd\ QuickFixCmdPost\ make w:\handmade\misc\build

  execute nr . 'wincmd w'
endfunction

nnoremap <silent> <C-b> :call <SID>build_handmade()<cr>

autocmd VimEnter * vs

function! s:handmade_syntax()
  syntax keyword Type DWORD LARGE_INTEGER HANDLE
  syntax keyword Keyword CALLBACk
endfunction

augroup handmade_hero
  autocmd!
  au FileType cpp call s:handmade_syntax()
augroup END
